# This workflow will install Python dependencies, run tests and lint.

name: Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ "*" ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --require-hashes -r requirements.txt
          pip install --require-hashes -r requirements-dev.txt
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check . --select=E9,F63,F7,F82 --target-version=py313
          # default set of ruff rules with GitHub Annotations
          ruff check . --target-version=py313
      - name: Unit Test Coverage
        run: |
          coverage run -m unittest discover -v -s tests/ -p 'test_*.py'
          coverage report -m gauge_api_steps/*.py
